package com.phonepe.growth.magazine.exception;

public enum ErrorCode {
    CONNECTION_ERROR,
    INTERNAL_ERROR,
    RETRIES_EXHAUSTED,
    MAGAZINE_UNPREPARED,
    NOTHING_TO_FIRE,
    MAGAZINE_NOT_FOUND,
    STORAGE_TYPE_MISMATCH,
    LOAD_ERROR,
    ACTION_DENIED_PARALLEL_ATTEMPT
}
