image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-17

.default: &default
  only:
    - merge_requests
    - web

.default_tag: &default_tag
  tags:
    - backend-docker

stages:
  - build
  - quality
  - deploy
  - merge
  - release

Build Package:
  stage: build
  <<: *default
  <<: *default_tag
  script:
    - mvn clean package -U -DskipTests=true
  except:
    - master
    - develop
  artifacts:
    paths:
      - "*/target"
    expire_in: "30 mins"


Pre Merge:
  stage: quality
  <<: *default_tag
  only:
    - merge_requests
  script:
    - mvn clean verify -U -Pquality_check -Dsonar.pullrequest.key=$CI_MERGE_REQUEST_ID -Dsonar.pullrequest.branch=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -Dsonar.pullrequest.base=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME

Deploy Snapshot:
  stage: deploy
  <<: *default
  <<: *default_tag
  script:
    - mvn deploy -DskipTests=true
  when: manual

Post Merge:
  stage: merge
  <<: *default_tag
  script:
    - mvn clean verify -U -Pquality_check -Dsonar.branch.name=$CI_COMMIT_BRANCH
  only:
    refs:
      - develop

release:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull origin master
    - git checkout develop
    - git pull origin develop
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop